### ISSUE TITLE
Too many Impact Statements

### ISSUE THREAD

**Issue by earlng** [earlng/academic-pdf-scrap#17]
If there are two different parts of the paper that both have a title that included “impact”, the new code will concatenate both and pull that combination in as the BIS

1. 196f5641aa9dc87067da4ff90fd81e7b
2. 274e6fcf4a583de4a81c6376f17673e7
3. 33a5435d4f945aa6154b31a73bab3b73
4. 93d9033636450402d67cd55e60b3f926
5. A03fa30821986dff10fc66647c84c9c3
6. B607ba543ad05417b8507ee86c54fcb7

**Comment by paulsedille** [comment]
I can't find a clear way to deal with this and more importantly, given that when this happened in previous outputs, I fixed it already, there would be little gain in "solving" this issue (I likely wouldn't find any 'fresh' errors). We can park it for now.
