### ISSUE TITLE
Scrape impact statements by looking for statements with "impact" in the title

### ISSUE THREAD

**Issue by paulsedille** [earlng/academic-pdf-scrap#2]
**Is your feature request related to a problem? Please describe.**
Currently the statements scraped are those with "broader impact(s)" in the title, would like to get all those with impact (case insensitive) in the title. 

**Describe the solution you'd like**
code scraps all occurrences of a section that has "impact" in its header

**Describe alternatives you've considered**
using the "if X in Y" function?

**Comment by earlng** [comment]
#4 resolves it.
